Self-Mullineux-SUBS
===================

The file 'selfmuBG.g' is a sequence of functions written in https://www.gap-system.org/[GAP 3] to compute the bijection 
`EBeta` which takes a prime (or odd integer) e and a self-Mullineux partition and returns the (unique) BG-partition associated under the correspondence defined in https://www.combinatorics.org/ojs/index.php/eljc/article/view/v28i1p57[this paper.]

To use this functions open gap3 in the folder containing 'selfmuBG.g' and do 

    Read("selfmuBG.g");

Then, any of the functions below can be used.

WARNING: The algorithms defining these functions are *not* the most efficient for computing the combinatorial objects associated.

.Functions
* `DiagramPartition(mu)`: Takes a partition `mu` and returns the set of nodes that form the Young diagram of `mu`.

* `Rim(mu)`:  Takes a partition `mu` and returns the set of nodes (i,j) of the rim of `mu`.

* `OrgRim(mu)`: Takes a partition `mu` and returns a list of the nodes of the rim of the diagram of `mu`, organized from "north-east" to "south-west" of the Young diagram.

* `HookLength(la,i,j)`: Takes a partition `la` and a node (i,j) in the Young diagram of `la` and returns the hook-length of the (i,j)-th hook.

* `PartitionDiag(nodes)`: Takes a set of nodes forming a Young diagram and returns the associated partition.


* `DiagBoxRim(mu)`: Takes a self-conjugate partition `mu` an returns i the only diagonal where (i,i) is the only diagonal node in the rim of `mu`.

* `PRim1(e,mu)`: Set U of the p-rim* of `mu`.

* `PRim2(l,e)`: Fix the middle segment.

* `PRim(e,mu)`: The subset U of the p-rim*.

* `PRim4(e,mu)`: The reflection of subset U of the p-rim*

* `PRim5(e,mu)`: p-rim* for self-conjugate `mu`.

* `ERim(e,mu)`: Takes an odd prime `e` and a self-conjugate partition `mu` and returns [mu^(1)* ,e-rim*] where e-rim is the e-rim* of a self-conjugate partition and `mu`^(1)* is the partition obtained from `mu` after deleting the e-rim*.

* `AutoSymb(e,mu)`: takes a prime `e` and a self-conjugate partition `mu` and returns the first line of the p-BG-symbol (first line) for `mu`.


* `EBGsymb(p,mu)`: Takes a prime `p` and a self-conjugate partition `mu` and returns the p-BG-symbol mu.

* `EBetaInverse(e,la)`: Takes an odd prime `e`, and a e-BG-partition `la` and returns the e-self-Mullineux partition corresponding to la under the bijection defined by the bg-symbol.

* `DurfeeNumber(mu)`: takes a partition and returns its Durfee number.

* `EBGPartitions(p,n)`: Takes an odd prime `p` and an integer `n` and returns the list of pBG-partitions of `n`.

* `EBetaSymbol(e,symb)`:  Takes a prime `e` and the Mullineux symbol symb (list of rows) of a e-self-Mullineux partition and returns the associated e-BG-partition.

* `EBeta(e,mu)`: Takes a prime `e` and a e-self-Mullineux `mu` and returns the e-BG-partition partition corresponding to mu under the bijection defined by the bg-symbol.


== SUBS
(SUBS stands for _**s**table **u**nitriangular **b**asic **s**ets_. See https://arxiv.org/abs/2106.07215[this preprint] for more on SUBS.)

The following is a list of functions to test which blocks of the
symmetric group have _compatible/completely admissible transversals_.
 
* `BlockPartitionsCore(e,n,core)`: Takes an integer `e`<n and `n` and returns all partitions in the block of S_n corresponding to the core `core`.

* `BlockPartitionsWeightCore(e,w,core)`: Same as `BlockPartitionsCore`, but with the weight `w`.

* `BlockPartitionsCoreERegulars(e,n,core)`: Returns all e-regular partitions on a block with a given core.

* `BlockPartitionsWeightCoreERegulars(e,w,core)`: Same but with weight.

* `BlockPartitionsWeightCoreERegularsSM(e,w,core)`: Self-Mullineux partitions in the e-block with weight.

* `EWeightWPart(e,w,n)`: returns all e-regular partitions of integers less than n of e weight w.

* `ListECores(e,m)`: Returns the list of e-cores of rank up to `m`.

* `ListECoresSC(e,m)`: Returns the list of self-conjugate e-cores of rank up to `m`.

* `ECoresList(e,n)`: list of all the e-cores of partitions of `n`.

* `PartitionsByBlocks(e,n)` : list of all partitions of n organised by blocks (corresponding to e-cores).

* `SSet(e,w,core)`: Returns the list formed by partitions with e-core `core` and e-weight `w`.

* `SSetReg(e,w,core)`: Returns the list of e-regular partitions in `SSet(e,w,core)`.

* `AdmTransversals(e,w,core)`: Returns a list of all the possible admissible transversals for the e-block of weight w of the block corresponding to the core `core`.

* `Test1AdmTransversals(e,m)`: For testing if the above function gives in fact all admissible transversals we have to look for an example where there exists at least two adm. tr.  For this, the following function looks for a block where this happens.
The test function will look for e-blocks where the rank of the e-blocks goes up to `m`.

* `ComplAdmTransversals(e,w,core)`: Returns a list of completely admissible transversals of the e-core of weight `w` and core `core`.

* `Test1CompltAdmTransversals(e,m)`: tests if there are (and how many) completely admissible transversals for e-cores up to rank `m`.


* `Test1Proposition7Weight2(k,m)`: tests how many completely admissible transversals for every e-core with e every odd up to the odd k and every e-core with rank up to m.
// tested see file Test1Proposition7Weight2(11,15)

* `CompTransversals(e,w,core)`: Returns a list of all the possible compatible transversals for the e-block of weight `w` of the
block corresponding to the core `core`.





 